"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""


def main() -> int:
    prev = 0
    curr = 1
    sum_even_fibonacci = 0
    while prev + curr < 4000000:
        next = prev + curr
        prev = curr
        curr = next
        if curr % 2 == 0:
            sum_even_fibonacci += curr
    return sum_even_fibonacci


if __name__ == "__main__":
    print("Starting Problem 2")
    solution = main()
    print(f"The solution to problem 2 is {solution}")
